### ISSUE TITLE
安装推送插件时依赖安装cordova-plugin-jcore失败，能否将cordova-plugin-jcore下载到本地安装

### ISSUE THREAD

**Issue by li5454yong** [jpush/cordova-plugin-jcore#1]

**Comment by 349989153** [comment]
+1
Failed to install 'cordova-plugin-jcore': Error: ENOENT: no such file or directory, open '/App/platforms/android/AndroidManifest.xml'
可是cordova项目下/platforms/android根本没有AndroidManifest.xml这个文件

**Comment by 349989153** [comment]
猜测：需要AndroidManifest.xml是因为要把key写进去。所以手动补上应该就好。
另外，AndroidManifest. xml的正确路径是/App/platforms/android/app/src/AndroidManifest.xml

cordova -v 
8.0.0

**Comment by JoshLipan** [comment]
注意版本问题，Jcore v1.2.0开始支持cordova android 7.0.0 ，7.0.0之前的版本建议按照v1.1.12
